In [2]:
import pandas as pd
import numpy as np
import requests
import time
from datetime import datetime
import os
from tqdm.notebook import trange, tqdm

In [4]:

test_url = "https://www.pdga.com/players/stats?Year=2021&player_Class=All&Gender=All&Bracket=All&continent=All&Country=All&StateProv=All"

#pretend to be a browser
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get(test_url, headers=header)

test_tables = pd.read_html(r.text)

test_tables[0]

,Name,PDGA #,Rating,Year,Gender,Class,Division,Country,State/Province,Events,Points,Cash
0,J. Freeman,69509,1030,2021,Male,Pro,Open,United States,Colorado,33,28817,"$33,135.00"
1,N. Queen,68286,1026,2021,Male,Pro,Open,United States,North Carolina,35,28590,"$50,355.00"
2,G. Gurthie,13864,1031,2021,Male,Pro,Open,United States,Florida,30,28370,"$26,555.00"
3,P. McBeth,27523,1050,2021,Male,Pro,Open,United States,California,24,28310,"$88,903.00"
4,R. Wysocki,38008,1054,2021,Male,Pro,Open,United States,South Carolina,24,27930,"$79,429.00"
5,R. Newsom,88212,1024,2021,Male,Pro,Open,United States,North Carolina,36,27662,"$20,165.00"
6,J. Conrad,17295,1035,2021,Male,Pro,Open,United States,Virginia,28,27220,"$47,700.00"
7,A. Hammes,57365,1041,2021,Male,Pro,Open,United States,Wisconsin,26,26945,"$49,916.00"
8,L. Samson,59419,1012,2021,Male,Pro,Open,United States,Illinois,42,26765,"$15,577.00"
9,K. Jones,41760,1036,2021,Male,Pro,Open,United States,Arkansas,27,26555,"$38,838.00"
10,K. Klein,85132,1039,2021,Male,Pro,Open,United States,Michigan,29,26192,"$58,602.00"
11,C. Heimburg,45971,1048,2021,Male,Pro,Open,United States,Florida,24,26120,"$59,785.00"
12,N. Locastro,11534,1030,2021,Male,Pro,Open,United States,Missouri,25,25342,"$29,976.00"
13,E. Aderhold,121715,1021,2021,Male,Pro,Open,United States,South Dakota,28,25292,"$22,250.00"
14,C. White,81739,1022,2021,Male,Pro,Open,United States,Massachusetts,31,25035,"$18,801.00"
15,C. Dickerson,62467,1045,2021,Male,Pro,Open,United States,Tennessee,33,24715,"$48,607.00"
16,P. Ulibarri,27171,1028,2021,Male,Pro,Open,United States,Arizona,31,24710,"$23,929.00"
17,C. O'Reilly,99648,1014,2021,Male,Pro,Open,United States,Texas,34,24427,"$15,651.00"
18,A. Presnell,63765,1028,2021,Male,Pro,Open,United States,Missouri,38,24405,"$29,324.00"
19,M. Bell,48950,1026,2021,Male,Pro,Open,United States,California,29,24165,"$22,409.00"

In [5]:
'''
first page
https://www.pdga.com/players/stats?Year=2021&player_Class=All&Gender=All&Bracket=All&continent=All&Country=All&StateProv=All

second page
https://www.pdga.com/players/stats?Year=2021&player_Class=All&Gender=All&Bracket=All&continent=All&Country=All&StateProv=All&page=1

last page
https://www.pdga.com/players/stats?Year=2021&player_Class=All&Gender=All&Bracket=All&continent=All&Country=All&StateProv=All&page=6626

page=0 works for first page
iterate url pages over range(6627)
november: 6715 pages
'''
now_string = datetime.now().strftime("%d_%m_%y_%H-%M-%S")
filename = "pdga_player_stats_{}.csv".format(now_string)


df = pd.DataFrame()

for i in trange(6715):
    
    while True:
        try:
            time.sleep(3*np.random.beta(2,1,1)[0]) #Not strictly necessary, but good practice and polite
            url = "https://www.pdga.com/players/stats?Year=2021&player_Class=All&Gender=All&Bracket=All&continent=All&Country=All&StateProv=All&page={}".format(i)

            r = requests.get(url, headers=header)
            df1 = pd.read_html(r.text)[0] #take 0th item of tables list

            df = pd.concat([df, df1], ignore_index=True)
                
        except Exception as e:
            print("page {} failed with exception {}".format(i, e))
            time.sleep(30)
            continue
        break

df.to_csv(filename)
display(df)

  0%|          | 0/6716 [00:00<?, ?it/s]

page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found
page 6715 failed with exception No tables found

KeyboardInterrupt:

In [6]:
df.to_csv(filename)

now = datetime.now()
print(now.strftime("%d_%m_%y_%H:%M:%S"))

11_11_21_22:03:04

In [5]:
#Get Udisc data on disc golf courses per state

#https://udisc.com/blog/post/most-disc-golf-courses-per-capita-us-states

udisc_data_url = "https://udisc.com/blog/post/most-disc-golf-courses-per-capita-us-states"

#pretend to be a browser
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get(udisc_data_url, headers=header)
udisc_table = pd.read_html(r.text, header=0)[0]

#write to .csv
udisc_table.to_csv("./data/udisc_courses_perstate.csv")

6715